"""
make_report_4b.py
-------------------
Builds report_4b.md straight from results/hw4b_main_table_{dataset}.csv
and results/alpha_values_{dataset}.json -- every number generated, none
typed by hand, per the same submission rule as make_report.py. Leaves a
clearly-marked placeholder for the written discussion (HW4b deliverable 3).

Run after run_hw4b.py:
    python make_report_4b.py
Then convert report_4b.md -> report_4b.pdf, e.g.:
    pandoc report_4b.md -o ../report_4b.pdf
"""
import os
import csv
import json

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(HERE, "..", "results")
OUT_PATH = os.path.join(HERE, "..", "report_4b.md")

DATASETS = ["amazon", "classic", "reuters"]

DISCUSSION_TEMPLATE = """
### Discussion (deliverable 3)

<!-- Write 5-8 sentences here, referencing the numbers above:
- At which alpha does the combined method match exact WMD's accuracy,
  per dataset?
- What does that alpha cost in average shortlist size and estimated time?
- Does classic (the dataset with the largest distortion per HW3) need a
  larger alpha or larger shortlists than the others?
- Where does the combined method land on the accuracy-time trade-off
  relative to the two pure methods (FSW-1000 alone, WMD-W2 alone)? -->
"""

COLUMNS = ["row", "alpha", "mean_test_error", "std_test_error",
           "k_stars_per_split", "shortlist_mean", "shortlist_median",
           "shortlist_p95", "coverage_top10", "est_time_s"]


def read_csv_rows(path):
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return list(csv.DictReader(f))


def render_table(rows, columns):
    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join(["---"] * len(columns)) + " |"
    lines = [header, sep]
    for r in rows:
        lines.append("| " + " | ".join(str(r.get(c, "")) for c in columns) + " |")
    return "\n".join(lines)


def main():
    parts = ["# HW4b Report — FSW shortlist + exact-W2 rerank\n",
             "*Generated by `make_report_4b.py` from `results/`. Nothing "
             "below the tables was typed by hand except the discussion "
             "sections.*\n"]

    for dataset in DATASETS:
        parts.append(f"\n## {dataset}\n")

        alpha_path = os.path.join(RESULTS_DIR, f"alpha_values_{dataset}.json")
        if os.path.exists(alpha_path):
            with open(alpha_path) as f:
                alphas = json.load(f)
            parts.append("Alpha values used (from fresh FSW-1000/W2 ratio "
                          "stats, m=1000, 5000 sampled pairs):\n")
            for k, v in alphas.items():
                parts.append(f"- {k} = {v:.4f}")
            parts.append("")

        rows = read_csv_rows(os.path.join(RESULTS_DIR, f"hw4b_main_table_{dataset}.csv"))
        if rows is None:
            parts.append(f"*(no results/hw4b_main_table_{dataset}.csv yet — "
                          f"run run_hw4b.py --dataset {dataset})*\n")
            continue

        parts.append("### Main table (deliverable 1) + coverage (deliverable 2)\n")
        parts.append(render_table(rows, COLUMNS))
        parts.append(DISCUSSION_TEMPLATE)

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
