"""
make_report.py
---------------
Builds report.md straight from results/*.csv and figures/*.png -- so
every number in it is generated, not typed by hand, per the submission
rule in HW3/HW4 §"Submission format". Fills in the main table, the CV
curves, and the error-vs-m plot for each dataset, and the time table.
Leaves clearly-marked placeholders for the written discussion (HW4
deliverable 5), which is your interpretation, not a generated number.

Run after run_hw4.py has produced results/ and figures/:
    python make_report.py
Then convert report.md -> report.pdf, e.g.:
    pandoc report.md -o ../report.pdf
"""
import os
import csv

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(HERE, "..", "results")
FIG_DIR = os.path.join(HERE, "..", "figures")
OUT_PATH = os.path.join(HERE, "..", "report.md")

DATASETS = ["amazon", "classic", "reuters"]

DISCUSSION_TEMPLATE = """
### Discussion (deliverable 5)

<!-- Write 6-10 sentences here, referencing the numbers above:
- Does FSW match WMD's accuracy, and for which m?
- Is the gap to WMD-W2 different from the gap to WMD-W1?
- Do the CV-vs-k curves for FSW resemble WMD's in shape, or prefer
  different neighborhood sizes?
- How do the speed numbers compare, and what do the two tables
  together say about the accuracy-speed trade? -->
"""


def read_csv_rows(path):
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return list(csv.DictReader(f))


def render_table(rows, columns):
    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join(["---"] * len(columns)) + " |"
    lines = [header, sep]
    for r in rows:
        lines.append("| " + " | ".join(str(r.get(c, "")) for c in columns) + " |")
    return "\n".join(lines)


def main():
    parts = ["# HW4 Report\n",
             "*Generated by `make_report.py` from `results/` and "
             "`figures/`. Nothing below the tables/figures was typed "
             "by hand except the discussion sections.*\n"]

    for dataset in DATASETS:
        parts.append(f"\n## {dataset}\n")

        main_rows = read_csv_rows(
            os.path.join(RESULTS_DIR, f"main_table_{dataset}.csv"))
        if main_rows is None:
            parts.append(f"*(no results/main_table_{dataset}.csv yet — "
                          f"run run_hw4.py --dataset {dataset})*\n")
            continue

        parts.append("### Main table (deliverable 1)\n")
        parts.append(render_table(
            main_rows,
            ["distance", "mean_test_error", "std_test_error",
             "k_stars_per_split"]))

        cv_fig = os.path.join("figures", f"cv_curves_{dataset}.png")
        if os.path.exists(os.path.join(FIG_DIR, f"cv_curves_{dataset}.png")):
            parts.append(f"\n### CV curves (deliverable 2)\n")
            parts.append(f"![CV curves — {dataset}]({cv_fig})\n")

        m_fig = os.path.join("figures", f"error_vs_m_{dataset}.png")
        if os.path.exists(os.path.join(FIG_DIR, f"error_vs_m_{dataset}.png")):
            parts.append(f"\n### Error vs m (deliverable 3)\n")
            parts.append(f"![Error vs m — {dataset}]({m_fig})\n")

        time_rows = read_csv_rows(
            os.path.join(RESULTS_DIR, f"time_table_{dataset}.csv"))
        if time_rows is not None:
            parts.append("\n### Time table (deliverable 4)\n")
            parts.append(render_table(
                time_rows,
                ["row", "pre_embedding_mean_s", "pre_embedding_std_s",
                 "per_query_mean_s", "per_query_std_s", "n_queries",
                 "machine"]))

        parts.append(DISCUSSION_TEMPLATE)

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
